SCHEMA = {
    "card_metadata": [
        "card_metadata_creation_date",
        "card_metadata_version_number",
        "card_metadata_version_changes",
        "card_metadata_doi",
    ],
    "model_basic_information": [
        "model_basic_information_name",
        "model_basic_information_creation_date",
        "model_basic_information_version_number",
        "model_basic_information_version_changes",
        "model_basic_information_doi",
        "model_basic_information_model_scope_summary",
        "model_basic_information_model_scope_anatomical_site",
        "model_basic_information_clearance_type",
        "model_basic_information_clearance_approved_by_name",
        "model_basic_information_clearance_approved_by_institution",
        "model_basic_information_clearance_approved_by_contact_email",
        "model_basic_information_clearance_additional_information",
        "model_basic_information_intended_users",
        "model_basic_information_observed_limitations",
        "model_basic_information_potential_limitations",
        "model_basic_information_type_of_learning_architecture",
        "model_basic_information_developed_by_name",
        "model_basic_information_developed_by_institution",
        "model_basic_information_developed_by_email",
        "model_basic_information_conflict_of_interest",
        "model_basic_information_software_license",
        "model_basic_information_code_source",
        "model_basic_information_model_source",
        "model_basic_information_citation_details",
        "model_basic_information_url_info",
    ],
    "technical_specifications": [
        "technical_specifications_model_pipeline_summary",
        "technical_specifications_model_pipeline_figure",
        "technical_specifications_model_inputs",
        "technical_specifications_model_outputs",
        "technical_specifications_pre-processing",
        "technical_specifications_post-processing",
    ],
    "hw_and_sw": [
        "hw_and_sw_libraries_and_dependencies",
        "hw_and_sw_hardware_recommended",
        "hw_and_sw_inference_time_for_recommended_hw",
        "hw_and_sw_installation_getting_started",
        "hw_and_sw_environmental_impact",
    ],
    "training_data": [
        "training_data_model_name",
        "training_data_url_doi_to_model_card",
        "training_data_tuning_technique",
        "training_data_total_size",
        "training_data_number_of_patients",
        "training_data_source",
        "training_data_acquisition_period",
        "training_data_inclusion_exclusion_criteria",
        "training_data_type_of_data_augmentation",
        "training_data_strategy_for_data_augmentation",
        "training_data_url_info",
        "training_data_treatment_modality_train",
        "training_data_beam_configuration_energy",
        "training_data_dose_engine",
        "training_data_target_volumes_and_prescription",
        "training_data_number_of_fractions",
        "training_data_reference_standard",
        "training_data_reference_standard_qa",
        "training_data_reference_standard_qa_additional_information",
        "training_data_icd10_11",
        "training_data_tnm_staging",
        "training_data_age",
        "training_data_sex",
        "training_data_target_volume_cm3"
        "training_data_bmi",
        "training_data_additional_patient_info",
        "training_data_validation_strategy",
        "training_data_validation_data_partition",
        "training_data_weights_initialization",
        "training_data_epochs",
        "training_data_optimiser",
        "training_data_learning_rate",
        "training_data_train_and_validation_loss_curves",
        "training_data_model_choice_criteria",
        "training_data_inference_method",
    ]
}

LEARNING_ARCHITECTURE = {
    "total_number_trainable_parameters": "",
    "number_of_inputs": "",
    "input_content_list": [],
    # No hace falta mostrarlos pues se agrupan y se muestran en input_content_list
    # "input_content_custom_text":"",
    # "input_content_new_type":None,
    # "input_content_new_subtype":None,
    "additional_information_input_content": "",
    "input_format": "",
    "input_size": "",
    "number_of_outputs": "",
    "output_content_list": [],
    # No hace falta mostrarlos pues se agrupan y se muestran en output_content_list
    # "output_content_custom_text":"",
    # "output_content_new_type":None,
    # "output_content_new_subtype":None,
    "additional_information_output_content": "",
    "output_format": "",
    "output_size": "",
    "loss_function": "",
    "batch_size": "",
    "regularisation": "",
    "architecture_figure": None,
    "architecture_figure_appendix_note": "",
    "uncertainty_quantification_techniques": "",
    "explainability_techniques": "",
    "additional_information_ts": "",
    "citation_details_ts": "",
}

TRAINING_DATA_INPUT_OUTPUT_TS = {
    "image_resolution": "",
    "patient_positioning": "",
    "scanner_model": "",
    "scan_acquisition_parameters": "",
    "scan_reconstruction_parameters": "",
    "fov": "",
    }