[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
headless = true

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false

[menuItems]
reportABug = null
about = null
getHelp = null
# This removes the GitHub link
gitHub = null
